name: Tracer
description: MGH LCS App for JC Visits
version: 0.1.0+2019091701

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^8.5.0
  flutter_staggered_grid_view: ^0.2.7
  json_annotation: ^0.2.3
  http: any
  shared_preferences: ^0.4.2
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.6.1
  pull_to_refresh: ^1.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any

flutter:
  # TODO: Insert Fonts (103)

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/tracers-ko.png
    - assets/tracer-logo-ko.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
